events {
    worker_connections 1024;
}

http {
    upstream workers {
        least_conn;
        server worker:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://workers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}